name: owl
favicon: null
layout_spectrum: 0.6047868677414954
typography_spectrum: 0.49024
title: Owl Sky City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050608'
    - '#515151'
    - '#969696'
    - '#aa1d21'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
